"use client"

import { useState, useEffect, useRef, useContext } from 'react'
import { Send, Bot, Loader2, Sparkles, Clock, Calendar, GitBranch, ArrowRight, Trash2, Bell } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { ScrollArea } from '@/components/ui/scroll-area'
import { useQuery, useAction, useMutation, useConvex } from "convex/react";
import { api } from "@/convex/_generated/api";
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';
import { UserContext } from '@/app/_context/UserContext';

export default function ChatPanel({ 
    chronicleId, 
    onPreview, 
    onClearPreview, 
    onApplyPreview,
    previewActive,
    currentUserRole = "viewer"
}) {
    const { userData } = useContext(UserContext);
    const [input, setInput] = useState('');
    const [isTyping, setIsTyping] = useState(false);
    const scrollRef = useRef(null);
    const textareaRef = useRef(null);

    const messages = useQuery(api.messages.list, { chronicleId }) || [];
    const currentTasks = useQuery(api.tasks.listByChronicle, { chronicleId }) || [];
    
    const orchestrate = useAction(api.agents.orchestrate);
    const batchUpdateDates = useMutation(api.tasks.batchUpdateDates);
    const createTask = useMutation(api.tasks.create);
    const clearMessages = useMutation(api.messages.clear);
    const convex = useConvex();

    useEffect(() => {
        if (scrollRef.current) {
            const viewport = scrollRef.current.querySelector('[data-radix-scroll-area-viewport]');
            if (viewport) {
                viewport.scrollTop = viewport.scrollHeight;
            }
        }
    }, [messages, isTyping]);

    // Auto-resize chat input height
    useEffect(() => {
        if (textareaRef.current) {
            textareaRef.current.style.height = 'auto';
            textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 160)}px`;
        }
    }, [input]);

    const handleSend = async () => {
        if (!input.trim()) return;

        const userMsg = input;
        setInput('');
        setIsTyping(true);

        try {
            await orchestrate({
                chronicleId,
                userMessage: userMsg,
            });
        } catch (error) {
            console.error("Agent error:", error);
            toast.error("Failed to get timeline response from AI");
        } finally {
            setIsTyping(false);
        }
    };

    // Sandboxed Client Calculations
    const handlePreviewCreateTimeline = (code) => {
        const loadingToast = toast.loading("Drafting visual timeline blueprint...");
        try {
            // Self-healing: wrap return if code doesn't explicitly start with a return or function
            let cleanCode = code.trim();
            if (!cleanCode.includes("return") && cleanCode.startsWith("[")) {
                cleanCode = `return ${cleanCode}`;
            }
            
            const generateFn = new Function(cleanCode);
            const generatedTasks = generateFn();

            if (!Array.isArray(generatedTasks)) {
                throw new Error("Timeline generation code must return an array of task blocks");
            }

            // Standardize output
            const enriched = generatedTasks.map((t, idx) => ({
                ...t,
                _id: `preview_${idx}`, // Temporary ID for preview positioning
                dependencies: t.dependencies || [],
                status: t.status || "todo",
                notes: t.notes || "Draft task generated by Chronos AI",
                color: t.color || "violet",
                department: t.department || "Product"
            }));

            onPreview(enriched, "create_timeline", code);
            toast.success("Timeline preview generated. Switch dates or drag blocks in preview!", { id: loadingToast });
        } catch (e) {
            console.error("Timeline Generation Error:", e);
            toast.error(`Roadmapping failed: ${e.message}`, { id: loadingToast });
        }
    };

    const handlePreviewReschedule = (code) => {
        if (currentTasks.length === 0) {
            toast.error("No tasks currently available to reschedule.");
            return;
        }

        const loadingToast = toast.loading("Calculating self-healing date reflow...");
        try {
            // Clone active tasks to execute pure calculations
            const clonedTasks = JSON.parse(JSON.stringify(currentTasks));
            const reflowFn = new Function("data", code);
            const shiftedTasks = reflowFn(clonedTasks);

            if (!Array.isArray(shiftedTasks)) {
                throw new Error("Reschedule function must return an array of modified tasks");
            }

            onPreview(shiftedTasks, "reschedule", code);
            toast.success("Recursive reschedule calculated. Review shifted blocks (highlighted)!", { id: loadingToast });
        } catch (e) {
            console.error("Reschedule Sandboxed Error:", e);
            toast.error(`Rescheduling math failed: ${e.message}`, { id: loadingToast });
        }
    };

    const handleClearChat = async () => {
        try {
            await clearMessages({ chronicleId });
            toast.success("Conversation history cleared");
        } catch (e) {
            toast.error("Failed to clear history");
        }
    };

    return (
        <div className="flex flex-col h-full bg-slate-50 overflow-hidden w-full border-l-4 border-black">
            {/* Header */}
            <header className="p-4 border-b-4 border-black flex items-center justify-between shrink-0 bg-white">
                <div className="flex items-center gap-3">
                    <div className="w-9 h-9 border-2 border-black bg-violet-500 flex items-center justify-center shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                        <Bot className="w-5 h-5 text-white" />
                    </div>
                    <div>
                        <h3 className="text-sm font-black text-slate-950 leading-tight uppercase tracking-tight">Chronos Orchestrator</h3>
                        <div className="flex items-center gap-1.5">
                            <div className="w-1.5 h-1.5 rounded-full bg-violet-500 animate-pulse" />
                            <span className="text-[9px] font-black uppercase tracking-widest text-violet-750">Orchestrator Online</span>
                        </div>
                    </div>
                </div>
                
                {currentUserRole !== "viewer" && (
                    <Button 
                        variant="ghost" 
                        size="icon" 
                        onClick={handleClearChat}
                        title="Clear Chat History"
                        className="h-8 w-8 text-slate-500 hover:text-red-600 hover:bg-slate-100 rounded-lg"
                    >
                        <Trash2 className="w-4 h-4" />
                    </Button>
                )}
            </header>

            {/* Messages Area */}
            <ScrollArea ref={scrollRef} className="flex-1 p-4 bg-slate-50">
                <div className="space-y-6 max-w-2xl mx-auto pb-6">
                    {messages.length === 0 && (
                        <div className="py-16 flex flex-col items-center text-center space-y-4">
                            <div className="w-16 h-16 bg-white border-4 border-black flex items-center justify-center shadow-[4px_4px_0px_0px_rgba(156,0,255,1)]">
                                <Clock className="w-8 h-8 text-violet-500 animate-pulse" />
                            </div>
                            <div className="space-y-1.5 px-4">
                                <h3 className="font-black text-slate-900 uppercase tracking-tight text-lg">Talk to your timeline</h3>
                                <p className="text-xs font-bold text-slate-500 max-w-[260px] uppercase tracking-wide leading-relaxed">
                                    Draft roadmaps, trigger slack notifications, or slide dates recursively via conversation.
                                </p>
                            </div>
                            <div className="p-4 bg-white border-2 border-slate-200 text-left rounded-xl space-y-2 max-w-xs text-[10px] font-bold text-slate-600 uppercase tracking-wider shadow-sm">
                                <p className="text-violet-500 font-black">TRY ASKING:</p>
                                <p>• "Plan our SaaS web app release in 5 weeks across Engineering, Legal and PR tracks."</p>
                                <p>• "Frontend API block is delayed by 4 days, shift dates."</p>
                            </div>
                        </div>
                    )}

                    {messages.map((msg, i) => {
                        const isAssistant = msg.role === 'assistant';
                        const messageData = isAssistant && typeof msg.content === 'object' ? msg.content : { content: msg.content };
                        
                        // Render system triggers (Automations fired)
                        if (msg.role === 'system') {
                            const sysDetails = msg.content || {};
                            return (
                                <div key={i} className="flex justify-center my-3 animate-in fade-in zoom-in-95 duration-300">
                                    <div className="bg-amber-50 border-2 border-amber-200 text-amber-700 p-4 text-xs font-bold uppercase tracking-wider rounded-xl max-w-sm flex items-start gap-3 shadow-md">
                                        <Bell className="w-5 h-5 text-amber-500 shrink-0 mt-0.5 animate-bounce" />
                                        <div>
                                            <p className="font-black text-amber-600">{sysDetails.title}</p>
                                            <p className="text-[10px] text-amber-700/80 mt-1">{sysDetails.message}</p>
                                        </div>
                                    </div>
                                </div>
                            );
                        }

                        return (
                            <div key={i} className={cn(
                                "flex flex-col gap-2 animate-in fade-in slide-in-from-bottom-2 duration-300",
                                msg.role === 'user' ? "items-end" : "items-start"
                            )}>
                                <div className={cn(
                                    "max-w-[90%] rounded-none p-5 text-xs shadow-md border-4 border-black transition-all",
                                    msg.role === 'user' 
                                        ? "bg-violet-500 text-white shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]" 
                                        : "bg-white text-slate-900 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]"
                                )}>
                                    <div className={cn(
                                        "prose prose-sm max-w-none font-bold uppercase tracking-wide leading-relaxed",
                                        msg.role === 'user' ? "prose-invert" : "text-slate-800"
                                    )}>
                                        <ReactMarkdown remarkPlugins={[remarkGfm]}>
                                            {messageData.content}
                                        </ReactMarkdown>
                                    </div>

                                    {/* Action Box for Create Timeline */}
                                    {isAssistant && msg.type === 'create_timeline' && messageData.code && (
                                        <div className="mt-4 pt-4 border-t-2 border-slate-200 flex flex-col gap-2.5">
                                            <div className="flex items-center gap-2 text-[10px] font-black text-violet-600 uppercase tracking-widest bg-violet-50 p-2 border border-violet-200">
                                                <Calendar className="w-4 h-4 text-violet-500" />
                                                New Roadmap Layout Proposed
                                            </div>
                                            
                                            <div className="grid grid-cols-2 gap-2">
                                                <Button 
                                                    onClick={() => handlePreviewCreateTimeline(messageData.code)}
                                                    variant="outline"
                                                    className="border-violet-500 text-violet-600 hover:bg-violet-100/50 font-black uppercase tracking-widest text-[9px] h-9 rounded-none border-2"
                                                >
                                                    Preview Roadmap
                                                </Button>
                                                <Button 
                                                    onClick={onApplyPreview}
                                                    disabled={!previewActive || currentUserRole === "viewer"}
                                                    className="bg-violet-500 hover:bg-violet-600 text-white font-black uppercase tracking-widest text-[9px] h-9 rounded-none border-2 border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] disabled:opacity-50 disabled:cursor-not-allowed"
                                                >
                                                    {currentUserRole === "viewer" ? "Apply (Locked)" : "Apply & Save"}
                                                </Button>
                                            </div>
                                        </div>
                                    )}

                                    {/* Action Box for Rescheduling */}
                                    {isAssistant && msg.type === 'reschedule' && messageData.code && (
                                        <div className="mt-4 pt-4 border-t-2 border-slate-200 flex flex-col gap-2.5">
                                            <div className="flex items-center gap-2 text-[10px] font-black text-amber-700 uppercase tracking-widest bg-amber-50 p-2 border border-amber-200">
                                                <GitBranch className="w-4 h-4 text-amber-600" />
                                                Downstream Temporal Shifts Calculated
                                            </div>
                                            
                                            <div className="grid grid-cols-2 gap-2">
                                                <Button 
                                                    onClick={() => handlePreviewReschedule(messageData.code)}
                                                    variant="outline"
                                                    className="border-amber-600 text-amber-700 hover:bg-amber-100/50 font-black uppercase tracking-widest text-[9px] h-9 rounded-none border-2"
                                                >
                                                    Preview Reflow
                                                </Button>
                                                <Button 
                                                    onClick={onApplyPreview}
                                                    disabled={!previewActive || currentUserRole === "viewer"}
                                                    className="bg-violet-500 hover:bg-violet-600 text-white font-black uppercase tracking-widest text-[9px] h-9 rounded-none border-2 border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] disabled:opacity-50 disabled:cursor-not-allowed"
                                                >
                                                    {currentUserRole === "viewer" ? "Apply (Locked)" : "Apply Changes"}
                                                </Button>
                                            </div>
                                        </div>
                                    )}
                                </div>
                            </div>
                        );
                    })}

                    {isTyping && (
                        <div className="flex items-start gap-3 animate-in fade-in duration-200">
                            <div className="w-8 h-8 rounded-none border border-slate-350 bg-white flex items-center justify-center shrink-0">
                                <Bot className="w-4 h-4 text-slate-500 animate-pulse" />
                            </div>
                            <div className="bg-white border-4 border-black p-4 text-xs font-bold text-slate-500 uppercase tracking-wide shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]">
                                <div className="flex gap-1.5 items-center">
                                    <div className="w-1.5 h-1.5 bg-violet-500 rounded-full animate-bounce" />
                                    <div className="w-1.5 h-1.5 bg-violet-500 rounded-full animate-bounce [animation-delay:0.2s]" />
                                    <div className="w-1.5 h-1.5 bg-violet-500 rounded-full animate-bounce [animation-delay:0.4s]" />
                                    <span className="ml-2 text-[10px] text-slate-500 tracking-widest font-black">Orchestrating...</span>
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            </ScrollArea>

            {/* Input Area */}
            {currentUserRole === "viewer" ? (
                <div className="p-4 bg-white border-t-4 border-black shrink-0">
                    <div className="bg-amber-50 border-4 border-black p-4 text-[10px] font-black text-amber-700 uppercase tracking-widest text-center shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] flex items-center justify-center gap-3">
                        <span className="text-sm">🔒</span>
                        <span>Read-only workspace. Ask owner to elevate your role to Editor to chat with Chronos.</span>
                    </div>
                </div>
            ) : (
                <div className="p-4 bg-white border-t-4 border-black shrink-0">
                    <div className="relative flex items-center gap-2 max-w-2xl mx-auto">
                        <textarea
                            ref={textareaRef}
                            rows={1}
                            value={input}
                            onChange={(e) => setInput(e.target.value)}
                            onKeyDown={(e) => {
                                if (e.key === 'Enter' && !e.shiftKey) {
                                    e.preventDefault();
                                    handleSend();
                                }
                            }}
                            placeholder="Explain timeline constraints, shifts, or triggers..."
                            className="flex-1 bg-slate-50 border-2 border-black rounded-none px-4 py-[11px] text-xs focus:outline-none focus:ring-2 focus:ring-violet-500/20 transition-all text-slate-950 placeholder:text-slate-400 resize-none max-h-[160px] overflow-y-auto no-scrollbar font-bold uppercase tracking-tight"
                        />
                        <Button 
                            onClick={handleSend}
                            disabled={!input.trim() || isTyping}
                            className="bg-violet-500 hover:bg-violet-600 text-white rounded-none border-2 border-black w-10 h-10 p-0 shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] shrink-0"
                        >
                            {isTyping ? <Loader2 className="w-5 h-5 animate-spin" /> : <Send className="w-5 h-5" />}
                        </Button>
                    </div>
                    <div className="flex justify-between items-center text-[8px] text-slate-500 mt-2 font-black uppercase tracking-widest px-1">
                        <span>AI dates recalculate recursively using topological algorithms.</span>
                        {userData && (
                            <span className="font-black text-violet-500 shrink-0">{userData.credits ?? 0} Credits Left</span>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}
